# Generated by Django 5.1.2 on 2024-10-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_grade_id_alter_groupstudent_id_alter_lesson_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.SmallIntegerField(choices=[(10, '10'), (9, '9'), (8, '8'), (7, '7'), (6, '6'), (5, '5'), (4, '4'), (3, '3'), (2, '2')], verbose_name='Оценка'),
        ),
    ]
