# Generated by Django 5.1.2 on 2024-10-21 04:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_score_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='symbol',
            field=models.CharField(max_length=20, verbose_name='Символ'),
        ),
        migrations.AlterField(
            model_name='score',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.SmallIntegerField(choices=[(10, '10'), (9, '9'), (8, '8'), (7, '7'), (6, '6'), (5, '5'), (4, '4'), (3, '3'), (2, '2'), ('-1', 'q')], verbose_name='Оценка'),
        ),
    ]
