# Generated by Django 5.1.2 on 2024-10-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_grade_symbol_alter_score_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='created',
            field=models.DateField(verbose_name='Дата создания'),
        ),
    ]
