# Generated by Django 5.1.2 on 2024-10-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_score_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='symbol',
            field=models.CharField(max_length=50, verbose_name='Символ'),
        ),
    ]
