# Generated by Django 5.1.2 on 2024-11-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_alter_score_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.TextField(blank=True, null=True, verbose_name='Тема урока'),
        ),
    ]
