# Generated by Django 5.1.2 on 2024-11-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_lesson_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='lesson_topic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема урока'),
        ),
    ]
