# Generated by Django 5.1.2 on 2024-11-16 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_score_lesson_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата урока')),
                ('topic', models.TextField(verbose_name='Тема урока')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.groupstudent', verbose_name='Группа')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.lesson', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Тема урока',
                'verbose_name_plural': 'Темы уроков',
            },
        ),
    ]
