# Generated by Django 5.1.2 on 2024-11-16 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_lessontopic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessontopic',
            unique_together={('lesson', 'date')},
        ),
        migrations.AlterField(
            model_name='lessontopic',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='journal.lesson', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='lessontopic',
            name='topic',
            field=models.CharField(max_length=255, verbose_name='Тема урока'),
        ),
        migrations.RemoveField(
            model_name='lessontopic',
            name='group',
        ),
    ]
