# Generated by Django 5.1.2 on 2024-11-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_alter_lessontopic_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessontopic',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='lessontopic',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='lessontopic',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lessontopic',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.lesson'),
        ),
        migrations.AlterField(
            model_name='lessontopic',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
