# Generated by Django 5.1.2 on 2024-11-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_alter_lessontopic_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='lesson_topic',
        ),
    ]
