# Generated by Django 5.1.2 on 2024-11-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_remove_score_lesson_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='topic',
        ),
    ]
