# Generated by Django 5.1.2 on 2024-11-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_remove_lesson_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='attendance_score',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Оценка за посещаемость'),
        ),
    ]
