# Generated by Django 5.1.2 on 2024-11-18 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_score_attendance_score'),
        ('people', '0005_alter_user_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.student')),
            ],
        ),
    ]
