# Generated by Django 5.1.2 on 2024-11-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0018_attendancescore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='attendance_score',
        ),
    ]
