# Generated by Django 5.1.2 on 2024-11-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0019_remove_score_attendance_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancescore',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendancescore',
            name='score',
            field=models.CharField(max_length=5),
        ),
    ]
