# Generated by Django 5.1.2 on 2024-11-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0020_alter_attendancescore_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancescore',
            name='date',
        ),
    ]
