# Generated by Django 5.1.2 on 2024-11-22 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0022_alter_attendancescore_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancescore',
            options={'verbose_name': 'Оценка посещаемости', 'verbose_name_plural': 'Оценки посещаемости'},
        ),
        migrations.AlterField(
            model_name='attendancescore',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='attendancescore',
            name='score',
            field=models.IntegerField(verbose_name='Посещаемость'),
        ),
        migrations.AlterField(
            model_name='attendancescore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_scores', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
    ]
