# Generated by Django 5.1.2 on 2024-11-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0023_alter_attendancescore_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='symbol',
            field=models.CharField(max_length=250, verbose_name='Символ'),
        ),
    ]
