# Generated by Django 5.1.2 on 2024-11-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0024_alter_grade_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='is_sum',
            field=models.BooleanField(default=False),
        ),
    ]
