# Generated by Django 5.1.2 on 2024-11-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0025_score_is_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='created',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания'),
        ),
    ]
