# Generated by Django 5.1.2 on 2024-11-25 16:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0026_alter_score_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='is_sum',
        ),
        migrations.AlterField(
            model_name='score',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
