# Generated by Django 5.1.2 on 2024-11-25 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0027_remove_score_is_sum_alter_score_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SumScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Сумма')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.groupstudent', verbose_name='Наименование класса')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.lesson', verbose_name='Урок')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sum_scores', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sum_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Оценка за сумму',
                'verbose_name_plural': 'Оценки за сумму',
            },
        ),
    ]
