# Generated by Django 5.1.2 on 2024-11-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0028_sumscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sumscore',
            name='created',
        ),
        migrations.RemoveField(
            model_name='sumscore',
            name='group',
        ),
        migrations.RemoveField(
            model_name='sumscore',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='sumscore',
            name='updated',
        ),
    ]
