# Generated by Django 5.1.2 on 2024-10-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='mailing_attachments/', verbose_name='Вложение'),
        ),
    ]
