# Generated by Django 5.1.2 on 2024-10-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_contact_id_alter_student_id_alter_teacher_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('teacher', 'Учитель'), ('student', 'Студент')], max_length=15, verbose_name='Статус поль'),
        ),
    ]
