# Generated by Django 5.1.2 on 2024-10-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_user_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('teacher', 'Учитель'), ('student', 'Студент')], max_length=15, verbose_name='Статус пользователя'),
        ),
    ]
