# Generated by Django 5.1.2 on 2024-10-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_user_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('K', 'K'), ('Q', 'Q')], max_length=1, verbose_name='Пол'),
        ),
    ]
