# Generated by Django 5.1.2 on 2024-11-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_user_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone3',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=12, verbose_name='Телефон'),
        ),
    ]
